server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: member-svc
          uri: ENC(Fg5FIO+7/ekgqVR0nJ9BSmTSSoO3sbPE++GW/+of26lP1LX4lcyuCQ==)
          predicates:
            - Path=/hanaMbr/**
          filters:
            - name: MemberFilter
              args:
                baseMessage: Spring Cloud Gateway MemberFilter
                preLogger: true
                postLogger: true