server:
  port: 8081
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: member-svc
          uri: http://localhost:8082
          predicates:
            - Path=/hanaMbr/**
          filters:
            - name: MemberFilter
              args:
                baseMessage: Spring Cloud Gateway MemberFilter
                preLogger: true
                postLogger: true